site_name: mbed OS API reference

docs_dir: docs

pages:
- ['index.md','Introduction to the API reference']
- ['Analog_IO/index.md', 'Inputs and Outputs - Analog', 'Analog Inputs and Outputs']
- ['Analog_IO/AnalogIn.md', 'Inputs and Outputs - Analog', 'AnalogIn']
- ['Analog_IO/AnalogOut.md', 'Inputs and Outputs - Analog', 'AnalogOut']
- ['Digital_IO/index.md', 'Inputs and Outputs - Digital', 'Digital Inputs and Outputs']
- ['Digital_IO/DigitalIn.md', 'Inputs and Outputs - Digital', 'Digital - DigitalIN']
- ['Digital_IO/DigitalOut.md', 'Inputs and Outputs - Digital', 'Digital - DigitalOut']
- ['Digital_IO/DigitalInOut.md', 'Inputs and Outputs - Digital', 'Digital - DigitalInOut']
- ['Digital_IO/BusIn.md', 'Inputs and Outputs - Digital', 'Bus - BusIn']
- ['Digital_IO/BusOut.md', 'Inputs and Outputs - Digital', 'Bus - BusOut']
- ['Digital_IO/BusInOut.md', 'Inputs and Outputs - Digital', 'Bus - BusInOut']
- ['Digital_IO/PortIn.md', 'Inputs and Outputs - Digital', 'Port - PortIn']
- ['Digital_IO/PortOut.md', 'Inputs and Outputs - Digital', 'Port - PortOut']
- ['Digital_IO/PortInOut.md', 'Inputs and Outputs - Digital', 'Port - PortInOut']
- ['Digital_IO/PwmOut.md', 'Inputs and Outputs - Digital', 'PwmOut']
- ['Digital_IO/InterruptIn.md', 'Inputs and Outputs - Digital', 'InterruptIn']
- ['Digital_Interfaces/index.md', 'Digital Interfaces', 'Digital Interfaces']
- ['Timers/index.md', 'Timing Operations', 'Timing Operations']
- ['Timers/Timer.md', 'Timing Operations', 'Timer']
- ['Timers/Timeout.md', 'Timing Operations', 'Timeout']
- ['Timers/Ticker.md', 'Timing Operations', 'Ticker']
- ['Timers/Wait.md', 'Timing Operations', 'Wait']
- ['Timers/Time.md', 'Timing Operations', 'Time']
- ['Networking/Ethernet.md', 'Networking - Ethernet', 'Ethernet']
- ['Networking/EthernetInterface.md', 'Networking - Ethernet', 'The Ethernet Interface']
- ['Networking/TCP_UDP_Socket.md', 'Networking - Ethernet', 'TCP/UDP Socket']
- ['Networking/TCP_IP_Protocols.md.md', 'Networking - Ethernet', 'TCP/IP Protocols']
- ['RTOS/mbed_RTOS.md', 'Real-Time Operating System', 'RTOS']
- ['File_System/index.md', 'File Systems', 'File Systems']
- ['File_System/LocalFileSystem.md', 'File Systems', 'Local File System']
- ['File_System/SDFileSystem.md', 'File Systems', 'SD File System']
- ['Memory/index.md', 'Memory Models', 'Memory Models']
- ['Memory/mbed_Memory.md', 'Memory Models', 'mbed Memory']
- ['Memory/RTOS_Memory.md', 'Memory Models', 'RTOS Memory']
- ['USB/index.md', 'USB', 'USB Devices and Hosts']
- ['USBDevice/USBMouse.md', 'USB Device', 'USBMouse']
- ['USBDevice/USBKeyboard.md', 'USB Device', 'USBKeyboard']
- ['USBDevice/USBMouseKeyboard.md', 'USB Device', 'USBMouseKeyboard']
- ['USBDevice/USBHID.md', 'USB Device', 'USBHID']
- ['USBDevice/USBMIDI.md', 'USB Device', 'USBMIDI']
- ['USBDevice/USBSerial.md', 'USB Device', 'USBSerial']
- ['USBDevice/USBAudio.md', 'USB Device', 'USBAudio']
- ['USBDevice/USBMSD.md', 'USB Device', 'USBMSD']
- ['USBHost/USBHostMouse.md', 'USB Host', 'USBHostMouse']
- ['USBHost/USBHostKeyboard.md', 'USB Host', 'USBHostKeyboard']
- ['USBHost/USBHostMSDe.md', 'USB Host', 'USBHostMSD']
- ['USBHost/USBHostSerial.md', 'USB Host', 'USBHostSerial']
- ['USBHost/USBHostHub.md', 'USB Host', 'USBHostHub']







