site_name: mbed OS API reference

docs_dir: docs

pages:
- ['index.md','Introduction to the API reference']
- ['Analog_IO/index.md', 'Inputs and Outputs', 'Analog IO']
- ['Analog_IO/AnalogIn.md', 'Inputs and Outputs', 'AnalogIn']
- ['Analog_IO/AnalogOut.md', 'Inputs and Outputs', 'AnalogOut']
- ['Digital_IO/index.md', 'Inputs and Outputs', 'Digital IO']
- ['Digital_IO/DigitalIn.md', 'Inputs and Outputs', 'Digital - DigitalIN']
- ['Digital_IO/DigitalOut.md', 'Inputs and Outputs', 'Digital - DigitalOut']
- ['Digital_IO/DigitalInOut.md', 'Inputs and Outputs', 'Digital - DigitalInOut']
- ['Digital_IO/BusIn.md', 'Inputs and Outputs', 'Bus - BusIn']
- ['Digital_IO/BusOut.md', 'Inputs and Outputs', 'Bus - BusOut']
- ['Digital_IO/BusInOut.md', 'Inputs and Outputs', 'Bus - BusInOut']
- ['Digital_IO/PortIn.md', 'Inputs and Outputs', 'Port - PortIn']
- ['Digital_IO/PortOut.md', 'Inputs and Outputs', 'Port - PortOut']
- ['Digital_IO/PortInOut.md', 'Inputs and Outputs', 'Port - PortInOut']
- ['Digital_IO/PwmOut.md', 'Inputs and Outputs', 'PwmOut']
- ['Digital_IO/InterruptIn.md', 'Inputs and Outputs', 'InterruptIn']
- ['Digital_Interfaces/index.md', 'Inputs and Outputs', 'Digital Interfaces']
